import type {
  ConversationInfo,
  JobInfo,
  LogLine,
  Repo,
  WorktreeInfo,
} from "./types";

const now = Date.now();
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString();

export const mockRepos: Repo[] = [
  { id: "pocket-dev-guild", name: "Pocket Dev Guild", path: "/home/alex/repos/pocket-dev-guild" },
  { id: "atlas-api", name: "Atlas API", path: "/home/alex/repos/atlas-api" },
  { id: "marketing-site", name: "Marketing Site", path: "/home/alex/repos/marketing-site" },
];

export const mockWorktrees: Record<string, WorktreeInfo[]> = {
  "pocket-dev-guild": [
    {
      name: null,
      is_primary: true,
      path: "/home/alex/repos/pocket-dev-guild",
      branch: "main",
      head: "a1b2c3d4e5f60718293a4b5c6d7e8f90",
      bare: false,
      detached: false,
    },
    {
      name: "feature_mobile_ui",
      is_primary: false,
      path: "/home/alex/repos/pocket-dev-guild-worktrees/feature_mobile_ui",
      branch: "feature/mobile-ui",
      head: "1122334455667788991011121314151617",
      bare: false,
      detached: false,
    },
    {
      name: "hotfix_sse_reconnect",
      is_primary: false,
      path: "/home/alex/repos/pocket-dev-guild-worktrees/hotfix_sse_reconnect",
      branch: "Hotfix/sse-reconnect",
      head: "deadbeefcafebabe00112233445566778899",
      bare: false,
      detached: false,
    },
  ],
  "atlas-api": [
    {
      name: null,
      is_primary: true,
      path: "/home/alex/repos/atlas-api",
      branch: "main",
      head: "fedcba0987654321",
      bare: false,
      detached: false,
    },
    {
      name: "feature_auth_v2",
      is_primary: false,
      path: "/home/alex/repos/atlas-api-worktrees/feature_auth_v2",
      branch: "feature/auth-v2",
      head: "0011223344556677",
      bare: false,
      detached: false,
    },
  ],
  "marketing-site": [
    {
      name: null,
      is_primary: true,
      path: "/home/alex/repos/marketing-site",
      branch: "main",
      head: "8899aabbccddeeff",
      bare: false,
      detached: false,
    },
  ],
};

export const mockConversations: ConversationInfo[] = [
  {
    id: "conv-001",
    repo_id: "pocket-dev-guild",
    worktree: "feature_mobile_ui",
    agent_id: null,
    title: "Mobile-first UI implementation",
    session_id: "session-pdg-001",
    summary:
      "Refactoring the static frontend into a Vite + React mobile-first PWA. Bottom nav and SSE log viewer are in place.",
    archived: false,
    created_at: iso(-1000 * 60 * 60 * 26),
    updated_at: iso(-1000 * 60 * 8),
    turns: ["job-001", "job-002", "job-003"],
  },
  {
    id: "conv-002",
    repo_id: "atlas-api",
    worktree: "feature_auth_v2",
    agent_id: null,
    title: "JWT auth + refresh tokens",
    session_id: "session-atlas-002",
    summary:
      "Adding rotating refresh tokens, RS256 signing, and a /auth/introspect endpoint compatible with the gateway.",
    archived: false,
    created_at: iso(-1000 * 60 * 60 * 50),
    updated_at: iso(-1000 * 60 * 60 * 2),
    turns: ["job-004", "job-005"],
  },
  {
    id: "conv-003",
    repo_id: "pocket-dev-guild",
    worktree: "hotfix_sse_reconnect",
    agent_id: null,
    title: "Fix SSE reconnect on iOS Safari",
    session_id: null,
    summary: "Investigating why EventSource stalls when the app returns from background on iOS 17.",
    archived: false,
    created_at: iso(-1000 * 60 * 60 * 5),
    updated_at: iso(-1000 * 60 * 60 * 5),
    turns: ["job-006"],
  },
  {
    id: "conv-004",
    repo_id: "marketing-site",
    worktree: null,
    agent_id: null,
    title: "Pricing page copy refresh",
    session_id: "session-mkt-004",
    summary: "Tightening the value props on the pricing page and adding a comparison table.",
    archived: false,
    created_at: iso(-1000 * 60 * 60 * 96),
    updated_at: iso(-1000 * 60 * 60 * 80),
    turns: ["job-007"],
  },
];

export const mockJobs: JobInfo[] = [
  {
    id: "job-001",
    repo_id: "pocket-dev-guild",
    worktree: "feature_mobile_ui",
    prompt: "Scaffold the React app with bottom navigation and the four main screens.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 25),
    finished_at: iso(-1000 * 60 * 60 * 24),
    conversation_id: "conv-001",
    request_id: "req-001",
    session_id: "session-pdg-001",
  },
  {
    id: "job-002",
    repo_id: "pocket-dev-guild",
    worktree: "feature_mobile_ui",
    prompt: "Wire up TanStack Query with a typed mock API client.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 12),
    finished_at: iso(-1000 * 60 * 60 * 11),
    conversation_id: "conv-001",
    request_id: "req-002",
    session_id: "session-pdg-001",
  },
  {
    id: "job-003",
    repo_id: "pocket-dev-guild",
    worktree: "feature_mobile_ui",
    prompt: "Add the SSE log viewer with auto-scroll and ANSI rendering.",
    status: "running",
    returncode: null,
    created_at: iso(-1000 * 60 * 8),
    finished_at: null,
    conversation_id: "conv-001",
    request_id: "req-003",
    session_id: "session-pdg-001",
  },
  {
    id: "job-004",
    repo_id: "atlas-api",
    worktree: "feature_auth_v2",
    prompt: "Add JWT issuance with RS256 and a JWKS endpoint.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 5),
    finished_at: iso(-1000 * 60 * 60 * 4),
    conversation_id: "conv-002",
    request_id: "req-004",
    session_id: "session-atlas-002",
  },
  {
    id: "job-005",
    repo_id: "atlas-api",
    worktree: "feature_auth_v2",
    prompt: "Add refresh-token rotation and reuse detection.",
    status: "failed",
    returncode: 1,
    created_at: iso(-1000 * 60 * 60 * 3),
    finished_at: iso(-1000 * 60 * 60 * 2),
    conversation_id: "conv-002",
    request_id: "req-005",
    session_id: "session-atlas-002",
  },
  {
    id: "job-006",
    repo_id: "pocket-dev-guild",
    worktree: "hotfix_sse_reconnect",
    prompt: "Reproduce the iOS Safari EventSource stall and propose a fix.",
    status: "queued",
    returncode: null,
    created_at: iso(-1000 * 60 * 2),
    finished_at: null,
    conversation_id: "conv-003",
    request_id: "req-006",
    session_id: null,
  },
  {
    id: "job-007",
    repo_id: "marketing-site",
    worktree: null,
    prompt: "Rewrite the hero copy on the pricing page to lead with outcomes.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 84),
    finished_at: iso(-1000 * 60 * 60 * 80),
    conversation_id: "conv-004",
    request_id: "req-007",
    session_id: "session-mkt-004",
  },
];

export const mockJobLogs: Record<string, LogLine[]> = {
  "job-001": [
    { stream: "stdout", line: "› auggie scaffold --template react-mobile\n" },
    { stream: "stdout", line: "✔ Created src/routes/_app.tsx\n" },
    { stream: "stdout", line: "✔ Created bottom navigation component\n" },
    { stream: "stdout", line: "✔ Wired four primary screens\n" },
    { stream: "stdout", line: "Done in 42.1s.\n" },
  ],
  "job-002": [
    { stream: "stdout", line: "› auggie wire-api\n" },
    { stream: "stdout", line: "✔ Generated typed client from openapi.json\n" },
    { stream: "stdout", line: "✔ Added TanStack Query hooks\n" },
    { stream: "stdout", line: "Done in 18.7s.\n" },
  ],
  "job-003": [
    { stream: "stdout", line: "› auggie implement log-viewer\n" },
    { stream: "stdout", line: "Reading FRONTEND.md…\n" },
    { stream: "stdout", line: "Planning component tree.\n" },
    { stream: "stdout", line: "Installing ansi-to-react…\n" },
    { stream: "stderr", line: "warn  peer dependency react@^18 satisfied by react@19\n" },
    { stream: "stdout", line: "Writing src/components/log-viewer.tsx\n" },
    { stream: "stdout", line: "Connecting EventSource(/jobs/job-003/events)\n" },
    { stream: "stdout", line: "Streaming…\n" },
  ],
  "job-004": [
    { stream: "stdout", line: "› auggie implement jwt-rs256\n" },
    { stream: "stdout", line: "✔ Generated RSA keypair\n" },
    { stream: "stdout", line: "✔ Added /.well-known/jwks.json\n" },
    { stream: "stdout", line: "✔ All tests passing\n" },
  ],
  "job-005": [
    { stream: "stdout", line: "› auggie implement refresh-rotation\n" },
    { stream: "stdout", line: "Editing src/auth/refresh.py\n" },
    { stream: "stderr", line: "ERROR  tests/test_refresh.py::test_reuse_detected FAILED\n" },
    { stream: "stderr", line: "AssertionError: expected reuse to revoke entire family\n" },
    { stream: "stdout", line: "Exiting with code 1.\n" },
  ],
  "job-006": [],
  "job-007": [
    { stream: "stdout", line: "› auggie rewrite-hero\n" },
    { stream: "stdout", line: "✔ Updated src/pricing/Hero.tsx\n" },
    { stream: "stdout", line: "✔ Updated copy.json\n" },
  ],
};