import type { ConversationInfo, JobInfo, LogLine, Repo, WorktreeInfo } from "./types";

const now = Date.now();
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString();

export const mockRepos: Repo[] = [
  { id: "pocket-dev-guild", name: "Pocket Dev Guild", path: "/home/alex/repos/pocket-dev-guild" },
  { id: "atlas-api", name: "Atlas API", path: "/home/alex/repos/atlas-api" },
  { id: "marketing-site", name: "Marketing Site", path: "/home/alex/repos/marketing-site" },
];

export const mockWorktrees: Record<string, WorktreeInfo[]> = {
  "pocket-dev-guild": [
    {
      name: null,
      is_primary: true,
      path: "/home/alex/repos/pocket-dev-guild",
      branch: "main",
      head: "a1b2c3d4e5f60718293a4b5c6d7e8f90",
      bare: false,
      detached: false,
    },
    {
      name: "feature_mobile_ui",
      is_primary: false,
      path: "/home/alex/repos/pocket-dev-guild-worktrees/feature_mobile_ui",
      branch: "feature/mobile-ui",
      head: "1122334455667788991011121314151617",
      bare: false,
      detached: false,
    },
    {
      name: "hotfix_sse_reconnect",
      is_primary: false,
      path: "/home/alex/repos/pocket-dev-guild-worktrees/hotfix_sse_reconnect",
      branch: "Hotfix/sse-reconnect",
      head: "deadbeefcafebabe00112233445566778899",
      bare: false,
      detached: false,
    },
  ],
  "atlas-api": [
    {
      name: null,
      is_primary: true,
      path: "/home/alex/repos/atlas-api",
      branch: "main",
      head: "fedcba0987654321",
      bare: false,
      detached: false,
    },
    {
      name: "feature_auth_v2",
      is_primary: false,
      path: "/home/alex/repos/atlas-api-worktrees/feature_auth_v2",
      branch: "feature/auth-v2",
      head: "0011223344556677",
      bare: false,
      detached: false,
    },
  ],
  "marketing-site": [
    {
      name: null,
      is_primary: true,
      path: "/home/alex/repos/marketing-site",
      branch: "main",
      head: "8899aabbccddeeff",
      bare: false,
      detached: false,
    },
  ],
};

export const mockConversations: ConversationInfo[] = [
  {
    id: "conv-001",
    repo_id: "pocket-dev-guild",
    worktree: "feature_mobile_ui",
    agent_id: null,
    title: "Mobile-first UI implementation",
    session_id: "session-pdg-001",
    summary:
      "Refactoring the static frontend into a Vite + React mobile-first PWA. Bottom nav and SSE log viewer are in place.",
    archived: false,
    created_at: iso(-1000 * 60 * 60 * 26),
    updated_at: iso(-1000 * 60 * 8),
    turns: ["job-001", "job-002", "job-003"],
    last_turn_status: "running",
  },
  {
    id: "conv-002",
    repo_id: "atlas-api",
    worktree: "feature_auth_v2",
    agent_id: null,
    title: "JWT auth + refresh tokens",
    session_id: "session-atlas-002",
    summary:
      "Adding rotating refresh tokens, RS256 signing, and a /auth/introspect endpoint compatible with the gateway.",
    archived: false,
    created_at: iso(-1000 * 60 * 60 * 50),
    updated_at: iso(-1000 * 60 * 60 * 2),
    turns: ["job-004", "job-005"],
    last_turn_status: "failed",
  },
  {
    id: "conv-003",
    repo_id: "pocket-dev-guild",
    worktree: "hotfix_sse_reconnect",
    agent_id: null,
    title: "Fix SSE reconnect on iOS Safari",
    session_id: null,
    summary: "Investigating why EventSource stalls when the app returns from background on iOS 17.",
    archived: false,
    created_at: iso(-1000 * 60 * 60 * 5),
    updated_at: iso(-1000 * 60 * 60 * 5),
    turns: ["job-006"],
    last_turn_status: "queued",
  },
  {
    id: "conv-004",
    repo_id: "marketing-site",
    worktree: null,
    agent_id: null,
    title: "Pricing page copy refresh",
    session_id: "session-mkt-004",
    summary: "Tightening the value props on the pricing page and adding a comparison table.",
    archived: false,
    created_at: iso(-1000 * 60 * 60 * 96),
    updated_at: iso(-1000 * 60 * 60 * 80),
    turns: ["job-007"],
    last_turn_status: "finished",
  },
  {
    id: "conv-005",
    repo_id: "pocket-dev-guild",
    worktree: null,
    agent_id: null,
    title: "Initial project setup",
    session_id: "session-pdg-005",
    summary: "Set up the initial Vite + React + TypeScript project structure with routing and basic layout.",
    archived: true,
    created_at: iso(-1000 * 60 * 60 * 24 * 30),
    updated_at: iso(-1000 * 60 * 60 * 24 * 28),
    turns: ["job-008", "job-009"],
    last_turn_status: "finished",
  },
  {
    id: "conv-006",
    repo_id: "atlas-api",
    worktree: null,
    agent_id: null,
    title: "Database migration framework",
    session_id: "session-atlas-006",
    summary: "Added Alembic migrations and set up the initial database schema for users and sessions.",
    archived: true,
    created_at: iso(-1000 * 60 * 60 * 24 * 45),
    updated_at: iso(-1000 * 60 * 60 * 24 * 42),
    turns: ["job-010"],
    last_turn_status: "finished",
  },
  {
    id: "conv-007",
    repo_id: "marketing-site",
    worktree: null,
    agent_id: null,
    title: "Blog redesign exploration",
    session_id: "session-mkt-007",
    summary: "Explored different blog layout options. Decided to go with a card-based grid layout.",
    archived: true,
    created_at: iso(-1000 * 60 * 60 * 24 * 60),
    updated_at: iso(-1000 * 60 * 60 * 24 * 58),
    turns: ["job-011", "job-012"],
    last_turn_status: "finished",
  },
];

export const mockJobs: JobInfo[] = [
  {
    id: "job-001",
    repo_id: "pocket-dev-guild",
    worktree: "feature_mobile_ui",
    prompt: "Scaffold the React app with bottom navigation and the four main screens.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 25),
    finished_at: iso(-1000 * 60 * 60 * 24),
    conversation_id: "conv-001",
    request_id: "req-001",
    session_id: "session-pdg-001",
  },
  {
    id: "job-002",
    repo_id: "pocket-dev-guild",
    worktree: "feature_mobile_ui",
    prompt: "Wire up TanStack Query with a typed mock API client.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 12),
    finished_at: iso(-1000 * 60 * 60 * 11),
    conversation_id: "conv-001",
    request_id: "req-002",
    session_id: "session-pdg-001",
  },
  {
    id: "job-003",
    repo_id: "pocket-dev-guild",
    worktree: "feature_mobile_ui",
    prompt: "Add the SSE log viewer with auto-scroll and ANSI rendering.",
    status: "running",
    returncode: null,
    created_at: iso(-1000 * 60 * 8),
    finished_at: null,
    conversation_id: "conv-001",
    request_id: "req-003",
    session_id: "session-pdg-001",
  },
  {
    id: "job-004",
    repo_id: "atlas-api",
    worktree: "feature_auth_v2",
    prompt: "Add JWT issuance with RS256 and a JWKS endpoint.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 5),
    finished_at: iso(-1000 * 60 * 60 * 4),
    conversation_id: "conv-002",
    request_id: "req-004",
    session_id: "session-atlas-002",
  },
  {
    id: "job-005",
    repo_id: "atlas-api",
    worktree: "feature_auth_v2",
    prompt: "Add refresh-token rotation and reuse detection.",
    status: "failed",
    returncode: 1,
    created_at: iso(-1000 * 60 * 60 * 3),
    finished_at: iso(-1000 * 60 * 60 * 2),
    conversation_id: "conv-002",
    request_id: "req-005",
    session_id: "session-atlas-002",
  },
  {
    id: "job-006",
    repo_id: "pocket-dev-guild",
    worktree: "hotfix_sse_reconnect",
    prompt: "Reproduce the iOS Safari EventSource stall and propose a fix.",
    status: "queued",
    returncode: null,
    created_at: iso(-1000 * 60 * 2),
    finished_at: null,
    conversation_id: "conv-003",
    request_id: "req-006",
    session_id: null,
  },
  {
    id: "job-007",
    repo_id: "marketing-site",
    worktree: null,
    prompt: "Rewrite the hero copy on the pricing page to lead with outcomes.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 84),
    finished_at: iso(-1000 * 60 * 60 * 80),
    conversation_id: "conv-004",
    request_id: "req-007",
    session_id: "session-mkt-004",
  },
  {
    id: "job-008",
    repo_id: "pocket-dev-guild",
    worktree: null,
    prompt: "Set up Vite + React + TypeScript project with TanStack Router.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 24 * 30),
    finished_at: iso(-1000 * 60 * 60 * 24 * 29),
    conversation_id: "conv-005",
    request_id: "req-008",
    session_id: "session-pdg-005",
  },
  {
    id: "job-009",
    repo_id: "pocket-dev-guild",
    worktree: null,
    prompt: "Add basic layout with header and navigation.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 24 * 28),
    finished_at: iso(-1000 * 60 * 60 * 24 * 28),
    conversation_id: "conv-005",
    request_id: "req-009",
    session_id: "session-pdg-005",
  },
  {
    id: "job-010",
    repo_id: "atlas-api",
    worktree: null,
    prompt: "Set up Alembic and create initial database schema.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 24 * 43),
    finished_at: iso(-1000 * 60 * 60 * 24 * 42),
    conversation_id: "conv-006",
    request_id: "req-010",
    session_id: "session-atlas-006",
  },
  {
    id: "job-011",
    repo_id: "marketing-site",
    worktree: null,
    prompt: "Create mockups for blog layout options.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 24 * 60),
    finished_at: iso(-1000 * 60 * 60 * 24 * 59),
    conversation_id: "conv-007",
    request_id: "req-011",
    session_id: "session-mkt-007",
  },
  {
    id: "job-012",
    repo_id: "marketing-site",
    worktree: null,
    prompt: "Implement card-based blog grid layout.",
    status: "finished",
    returncode: 0,
    created_at: iso(-1000 * 60 * 60 * 24 * 59),
    finished_at: iso(-1000 * 60 * 60 * 24 * 58),
    conversation_id: "conv-007",
    request_id: "req-012",
    session_id: "session-mkt-007",
  },
];

export const mockJobLogs: Record<string, LogLine[]> = {
  "job-001": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m auggie scaffold --template react-mobile\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Created src/routes/_app.tsx\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Created bottom navigation component\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Wired four primary screens\n" },
    { stream: "stdout", line: "\x1b[2mDone in 42.1s.\x1b[0m\n" },
  ],
  "job-002": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m auggie wire-api\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Generated typed client from openapi.json\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Added TanStack Query hooks\n" },
    { stream: "stdout", line: "\x1b[2mDone in 18.7s.\x1b[0m\n" },
  ],
  "job-003": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m auggie implement log-viewer\n" },
    { stream: "stdout", line: "# Task: Implement Log Viewer\n" },
    { stream: "stdout", line: "Reading \x1b[1mFRONTEND.md\x1b[0m…\n" },
    { stream: "stdout", line: "Planning component tree.\n" },
    { stream: "stdout", line: "\n" },
    { stream: "stdout", line: "\x1b[90m🔧 Tool call: codebase-retrieval\x1b[0m\n" },
    {
      stream: "stdout",
      line: '   information_request: "Log viewer components and ANSI rendering patterns"\n',
    },
    { stream: "stdout", line: "\n" },
    { stream: "stdout", line: "\x1b[90m📋 Tool result: codebase-retrieval\x1b[0m\n" },
    { stream: "stdout", line: "The following code sections were retrieved:\n" },
    { stream: "stdout", line: "Path: src/components/pdg/LogViewer.tsx\n" },
    { stream: "stdout", line: '     1  import { useEffect, useRef, useState } from "react";\n' },
    { stream: "stdout", line: '     2  import { pdg } from "@/lib/pdg/client";\n' },
    { stream: "stdout", line: "...\n" },
    { stream: "stdout", line: "\n" },
    { stream: "stdout", line: "🤖\n" },
    { stream: "stdout", line: "## Step 1: Dependencies\n" },
    { stream: "stdout", line: "Installing \x1b[33mansi-to-react\x1b[0m…\n" },
    {
      stream: "stderr",
      line: "\x1b[33mwarn\x1b[0m  peer dependency react@^18 satisfied by react@19\n",
    },
    { stream: "stdout", line: "\n" },
    { stream: "stdout", line: "\x1b[90m🔧 Tool call: str-replace-editor\x1b[0m\n" },
    { stream: "stdout", line: "   command: str_replace\n" },
    { stream: "stdout", line: "   path: src/components/pdg/LogViewer.tsx\n" },
    { stream: "stdout", line: "\n" },
    { stream: "stdout", line: "\x1b[90m📋 Tool result: str-replace-editor\x1b[0m\n" },
    { stream: "stdout", line: "Successfully edited the file.\n" },
    { stream: "stdout", line: "\n" },
    { stream: "stdout", line: "🤖\n" },
    { stream: "stdout", line: "## Step 2: Implementation\n" },
    { stream: "stdout", line: "### Writing Components\n" },
    { stream: "stdout", line: "Writing \x1b[36msrc/components/log-viewer.tsx\x1b[0m\n" },
    { stream: "stdout", line: "**Note:** Added ANSI parsing and markdown support\n" },
    { stream: "stdout", line: "### Testing Connection\n" },
    { stream: "stdout", line: "Connecting EventSource(\x1b[36m/jobs/job-003/events\x1b[0m)\n" },
    { stream: "stdout", line: "\x1b[1;32mStreaming…\x1b[0m\n" },
    { stream: "stdout", line: "\n" },
    { stream: "stdout", line: "---\n" },
    { stream: "stdout", line: "### Final Summary\n" },
    { stream: "stdout", line: "Successfully implemented the LogViewer component with:\n" },
    { stream: "stdout", line: "- ANSI color support\n" },
    { stream: "stdout", line: "- Markdown rendering\n" },
    { stream: "stdout", line: "- Collapsible sections for tool calls\n" },
  ],
  "job-004": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m auggie implement jwt-rs256\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Generated RSA keypair\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Added /.well-known/jwks.json\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m All tests passing\n" },
  ],
  "job-005": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m auggie implement refresh-rotation\n" },
    { stream: "stdout", line: "Editing src/auth/refresh.py\n" },
    {
      stream: "stderr",
      line: "\x1b[31mERROR\x1b[0m  tests/test_refresh.py::test_reuse_detected \x1b[1;31mFAILED\x1b[0m\n",
    },
    {
      stream: "stderr",
      line: "\x1b[31mAssertionError:\x1b[0m expected reuse to revoke entire family\n",
    },
    { stream: "stdout", line: "Exiting with code 1.\n" },
  ],
  "job-006": [],
  "job-007": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m auggie rewrite-hero\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Updated src/pricing/Hero.tsx\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Updated copy.json\n" },
  ],
  "job-008": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m npm create vite@latest . -- --template react-ts\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Project created\n" },
    { stream: "stdout", line: "\x1b[36m›\x1b[0m npm install @tanstack/react-router\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Dependencies installed\n" },
  ],
  "job-009": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m auggie scaffold-layout\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Created src/components/layout/AppShell.tsx\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Created navigation component\n" },
  ],
  "job-010": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m alembic init migrations\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Created migration environment\n" },
    { stream: "stdout", line: "\x1b[36m›\x1b[0m alembic revision --autogenerate -m \"Initial schema\"\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Generated migration\n" },
  ],
  "job-011": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m auggie design-mockup\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Created design mockups\n" },
  ],
  "job-012": [
    { stream: "stdout", line: "\x1b[36m›\x1b[0m auggie implement-blog-grid\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Created blog grid component\n" },
    { stream: "stdout", line: "\x1b[32m✔\x1b[0m Added responsive styles\n" },
  ],
};
