/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReposRouteImport } from './routes/_app.repos'
import { Route as AppJobsIndexRouteImport } from './routes/_app.jobs.index'
import { Route as AppConversationsIndexRouteImport } from './routes/_app.conversations.index'
import { Route as AppJobsIdRouteImport } from './routes/_app.jobs.$id'
import { Route as AppConversationsIdRouteImport } from './routes/_app.conversations.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReposRoute = AppReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsIndexRoute = AppConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsIdRoute = AppConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repos': typeof AppReposRoute
  '/conversations/$id': typeof AppConversationsIdRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/conversations/': typeof AppConversationsIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repos': typeof AppReposRoute
  '/conversations/$id': typeof AppConversationsIdRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/conversations': typeof AppConversationsIndexRoute
  '/jobs': typeof AppJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/repos': typeof AppReposRoute
  '/_app/conversations/$id': typeof AppConversationsIdRoute
  '/_app/jobs/$id': typeof AppJobsIdRoute
  '/_app/conversations/': typeof AppConversationsIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/repos'
    | '/conversations/$id'
    | '/jobs/$id'
    | '/conversations/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/repos'
    | '/conversations/$id'
    | '/jobs/$id'
    | '/conversations'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/repos'
    | '/_app/conversations/$id'
    | '/_app/jobs/$id'
    | '/_app/conversations/'
    | '/_app/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/repos': {
      id: '/_app/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof AppReposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations/': {
      id: '/_app/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AppConversationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations/$id': {
      id: '/_app/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof AppConversationsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppReposRoute: typeof AppReposRoute
  AppConversationsIdRoute: typeof AppConversationsIdRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppConversationsIndexRoute: typeof AppConversationsIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppReposRoute: AppReposRoute,
  AppConversationsIdRoute: AppConversationsIdRoute,
  AppJobsIdRoute: AppJobsIdRoute,
  AppConversationsIndexRoute: AppConversationsIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
